In [1]:
#https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
import numpy as np

print(np.ones((2,3,4),dtype=np.int16))
print(np.zeros((3,4)))
print(np.empty((2,3)))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [2]:
print(np.arange(10,30,5))
print(np.arange(0,2,0.3))

#从1到2之间，等分成9个
print(np.linspace(1,2,9))

from numpy import pi
x=np.linspace(0,2*pi,100)
f=np.sin(x)
print(f)

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.420

In [3]:
c = np.arange(24).reshape(2,3,4)
print(c)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
a=np.array([1,2,3,4,5])
a,a.T

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [5]:
years=np.array([[5], [3], [8], [1.4], [10.1]])
years,years.T

(array([[ 5. ],
        [ 3. ],
        [ 8. ],
        [ 1.4],
        [10.1]]), array([[ 5. ,  3. ,  8. ,  1.4, 10.1]]))

In [6]:
#append
#将base想象成一张图片
base=np.array([[[1, 2, 3],
                      [4, 5, 6]]])
base

array([[[1, 2, 3],
        [4, 5, 6]]])

In [7]:
#横向添加：增加图片宽度
np.append(base,[[[7,8,9]]],axis=1)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
#纵向添加，增加图片高度
np.append(base,[[[7,8,9],[10,11,12]]],axis=0)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
#增加图片宽度np.concatenate()——连结
np.concatenate((base,[[[13,14,15]]]),axis=1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15]]])

In [10]:
#增加图片深度np.concatenate()
# np.concatenate((base,np.array([[[13,14]]]).T),axis=2)

In [11]:
#图片通道合成
red=np.array([[1,2,3],[4,5,6]])
green=np.array([[7,8,9],[10,11,12]])
blue=np.array([[13,14,15],[16,17,18]])
red,green,blue

(array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([[13, 14, 15],
        [16, 17, 18]]))

In [12]:
#接下来呢？


In [13]:
#2d卷积计算signal.convolve2d()
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html
from scipy import signal
input_layer=np.array([[1,2,3],[3,4,5],[6,7,8]])
weights=np.array([[0.4,0.2],[0.3,0.3]])
signal.convolve(input_layer,weights)

array([[0.4, 1. , 1.6, 0.6],
       [1.5, 3.1, 4.3, 1.9],
       [3.3, 6.1, 7.3, 3.1],
       [1.8, 3.9, 4.5, 2.4]])

In [14]:
#nd卷积计算
#https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.filters.convolve.html
#scipy.ndimage.filters.convolve(input, weights, output=None, mode='reflect', cval=0.0, origin=0)[source]
import scipy

input_layer=np.array([[[1,2,3],[3,4,5],[6,7,8]],[[1,2,3],[3,4,5],[6,7,8]]])
weights=np.array([[[0.4,0.2],[0.3,0.3]]])
scipy.ndimage.filters.convolve(input_layer,weights)


array([[[3, 4, 4],
        [6, 7, 7],
        [7, 9, 9]],

       [[3, 4, 4],
        [6, 7, 7],
        [7, 9, 9]]])

# np.delete/insert/append

In [18]:

arr=np.array(np.arange(12).reshape([3,4]))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.delete(arr,[0,1],axis=0)

array([[ 8,  9, 10, 11]])

In [20]:
np.delete(arr,[0,1],axis=1)

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [21]:
#np.insert(目标数组，插入位置，插入值，插入维度)
np.insert(arr,2,[11,12,13],axis=1)

array([[ 0,  1, 11,  2,  3],
       [ 4,  5, 12,  6,  7],
       [ 8,  9, 13, 10, 11]])

In [23]:
#np.append()
np.append(arr,[[1,2,3,4]],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

In [27]:
np.append(arr,[[1],[2],[3]],axis=1)

array([[ 0,  1,  2,  3,  1],
       [ 4,  5,  6,  7,  2],
       [ 8,  9, 10, 11,  3]])

# 按照条件修改部分数据

In [36]:
arr=np.random.randint(-5,5,(5,5))
arr

array([[ 3, -3,  0,  2, -4],
       [ 4, -5, -1, -5,  0],
       [ 4,  3,  1, -1,  0],
       [ 3, -4,  2,  3, -5],
       [ 3, -5,  1, -1, -4]])

In [37]:
#将小于0的数据替换成0
np.maximum(arr,0)

array([[3, 0, 0, 2, 0],
       [4, 0, 0, 0, 0],
       [4, 3, 1, 0, 0],
       [3, 0, 2, 3, 0],
       [3, 0, 1, 0, 0]])

In [38]:
test=arr.copy()
test[test<0]=0
test

array([[3, 0, 0, 2, 0],
       [4, 0, 0, 0, 0],
       [4, 3, 1, 0, 0],
       [3, 0, 2, 3, 0],
       [3, 0, 1, 0, 0]])

In [39]:
np.where(arr>0,a,0)

array([[1, 0, 0, 4, 0],
       [1, 0, 0, 0, 0],
       [1, 2, 3, 0, 0],
       [1, 0, 3, 4, 0],
       [1, 0, 3, 0, 0]])

# numpy random
https://docs.scipy.org/doc/numpy/reference/routines.random.html

In [67]:
np.random.rand(1,2,3)

array([[[0.21279393, 0.65328924, 0.55629843],
        [0.24446369, 0.67812534, 0.18769472]]])

In [68]:
#正态分布
np.random.randn(1,2,3)

array([[[-0.15286603,  0.22408311, -0.00435165],
        [ 0.48551582,  2.26549273, -1.10350127]]])

In [71]:
np.random.randint(-5,5,(5,5))

array([[-4,  3, -1, -5, -2],
       [ 1,  0,  0, -2,  4],
       [-1,  4, -1, -5,  1],
       [-3, -1, -4, -5, -1],
       [ 1,  0, -5,  4,  3]])

In [72]:
np.random.random_integers(-5,5,(5,5))

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(-5, 5 + 1) instead
  """Entry point for launching an IPython kernel.


array([[ 1, -4,  2,  5, -5],
       [-2,  0, -4,  2,  0],
       [ 1, -1, -4,  3,  0],
       [-1,  5,  5, -1, -3],
       [-4,  5, -1,  5,  2]])

In [76]:
np.random.random([5,5])

array([[0.98932704, 0.78168639, 0.31611393, 0.10013692, 0.64862941],
       [0.3939528 , 0.13239622, 0.14316803, 0.27551434, 0.5016581 ],
       [0.03481797, 0.76423939, 0.12803655, 0.31479114, 0.56981643],
       [0.1855153 , 0.4139362 , 0.38612723, 0.93342813, 0.09393684],
       [0.9220396 , 0.25288619, 0.61508357, 0.85417096, 0.90894797]])

In [77]:
#第一个参数说明
#If an ndarray, a random sample is generated from its elements. 
#If an int, the random sample is generated as if a were np.arange(a)
np.random.choice(4,[2,3])

array([[1, 1, 2],
       [3, 2, 1]])

In [78]:
np.random.choice([12,11,1,3],[2,3])

array([[ 3,  1,  3],
       [11,  1,  1]])

In [111]:
#设置了seed，使得np.random.rand(2,3)运行的结果每次都相同
np.random.seed(1)
np.random.rand(2,3)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [104]:
np.random.rand(2,3)

array([[0.49157316, 0.05336255, 0.57411761],
       [0.14672857, 0.58930554, 0.69975836]])

In [86]:
test=np.random.randn(5,5)
test

array([[-0.0482517 ,  0.08160927,  1.11079721,  0.98412448, -0.84761977],
       [-0.31743957,  1.30986836, -1.17014753,  0.67063867, -0.60648108],
       [-0.14873981,  1.65830368, -0.18210251,  0.39490704,  0.98231445],
       [-1.07504556, -1.36940513, -0.41246808,  1.56045505, -0.51074614],
       [ 0.59849147, -1.09201393, -0.06345718, -0.550458  ,  0.64348035]])

In [87]:
#条件为True取前面那个值，条件为False取后面那个值
np.where(test<0.0,0,test)

array([[0.        , 0.08160927, 1.11079721, 0.98412448, 0.        ],
       [0.        , 1.30986836, 0.        , 0.67063867, 0.        ],
       [0.        , 1.65830368, 0.        , 0.39490704, 0.98231445],
       [0.        , 0.        , 0.        , 1.56045505, 0.        ],
       [0.59849147, 0.        , 0.        , 0.        , 0.64348035]])

In [112]:
#填充指定数字
np.full((3,4),15)

array([[15, 15, 15, 15],
       [15, 15, 15, 15],
       [15, 15, 15, 15]])

In [176]:
x,y=np.meshgrid(np.arange(-2,3),np.arange(-2,3))
x,y

(array([[-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2]]), array([[-2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2]]))

In [178]:
arr=np.rec.fromarrays([x,y])
arr.shape,arr

((5, 5), rec.array([[(-2, -2), (-1, -2), ( 0, -2), ( 1, -2), ( 2, -2)],
            [(-2, -1), (-1, -1), ( 0, -1), ( 1, -1), ( 2, -1)],
            [(-2,  0), (-1,  0), ( 0,  0), ( 1,  0), ( 2,  0)],
            [(-2,  1), (-1,  1), ( 0,  1), ( 1,  1), ( 2,  1)],
            [(-2,  2), (-1,  2), ( 0,  2), ( 1,  2), ( 2,  2)]],
           dtype=[('f0', '<i8'), ('f1', '<i8')]))

In [177]:
#numpy.apply_along_axis
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.apply_along_axis.html
import math
def radius(coord):
    return math.sqrt(pow(coord[0],2)+pow(coord[1],2))

test=np.apply_along_axis(radius,2,arr.tolist())
test

array([[2.82842712, 2.23606798, 2.        , 2.23606798, 2.82842712],
       [2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798],
       [2.        , 1.        , 0.        , 1.        , 2.        ],
       [2.23606798, 1.41421356, 1.        , 1.41421356, 2.23606798],
       [2.82842712, 2.23606798, 2.        , 2.23606798, 2.82842712]])