In [1]:
#https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
import numpy as np

print(np.ones((2,3,4),dtype=np.int16))
print(np.zeros((3,4)))
print(np.empty((2,3)))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[  1.39069238e-309   1.39069238e-309   1.39069238e-309]
 [  1.39069238e-309   1.39069238e-309   1.39069238e-309]]


In [2]:
print(np.arange(10,30,5))
print(np.arange(0,2,0.3))

#从1到2之间，等分成9个
print(np.linspace(1,2,9))

from numpy import pi
x=np.linspace(0,2*pi,100)
f=np.sin(x)
print(f)

[10 15 20 25]
[ 0.   0.3  0.6  0.9  1.2  1.5  1.8]
[ 1.     1.125  1.25   1.375  1.5    1.625  1.75   1.875  2.   ]
[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-01   1.58001396e-01
   9.50560433e-02   3.17279335e-02  -3.17279335e-02  -9.

In [4]:
c = np.arange(24).reshape(2,3,4)
print(c)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
a=np.array([1,2,3,4,5])
a,a.T

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [6]:
years=np.array([[5], [3], [8], [1.4], [10.1]])
years,years.T

(array([[  5. ],
        [  3. ],
        [  8. ],
        [  1.4],
        [ 10.1]]), array([[  5. ,   3. ,   8. ,   1.4,  10.1]]))