In [13]:
import tensorflow as tf

"""
错误重现：
TypeError: Failed to convert object of type <type 'list'> to Tensor. 
Contents: [None, 4]. 
Consider casting elements to a supported type.

运行环境：
docker run -d  --restart=always -p 8888:8888 tensorflow/tensorflow:1.4.0
"""
xs=tf.placeholder(tf.float32,[None,2,2,1],name='x-input')

# reshaped_xs=tf.reshape(xs,[None,4])
#解决办法：
reshaped_xs=tf.reshape(xs,[tf.shape(xs)[0],4])

import numpy as np
data=np.ones([3,2,2,1])

with tf.Session() as sess:
    print sess.run(reshaped_xs,feed_dict={xs:data})


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
