In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by yetongxue<yeli.studio@qq.com> on 2018/2/1 11:02


#https://www.zybuluo.com/hanbingtao/note/433855
import numpy as np
def f(x):
    '''
    定义激活函数f
    '''
    return 1 if x > 0 else 0

activator=f
weights=np.array([0.0 for _ in range(3)])

#datasets,基于and真值表构建训练数据
#注意第一个1是bias,后面两个对应x1,x2
input_vecs=np.array([[1,1,1],[1,1,0],[1,0,1],[1,0,0]])
# 期望的输出列表，注意要与输入一一对应
# [1,1,1] -> 1, [1,0,0] -> 0, [1,1,0] -> 0, [1,0,1] -> 0
labels = np.array([1, 0, 0, 0])

#输入训练数据：一组向量、与每个向量对应的label；以及训练轮数、学习率（10, 0.1）
# print(datasets[:,:-1])

for i in range(10):
    #计算感知器计算结果
    res_z=input_vecs.dot(weights.T)
    res_a=np.array(list(map(activator,res_z)))
    #更新权重
    #按照感知器规则更新权重
    dalta=labels-res_a
    dalta_update=dalta.dot(input_vecs)*0.1
    weights=weights+dalta_update
    print(weights)


[ 0.1  0.1  0.1]
[-0.2  0.   0. ]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]
[-0.1  0.1  0.1]


In [2]:
#验证
w=np.array([-0.1,0.1,0.1])
res_z=input_vecs.dot(w.T)
res_a=np.array(list(map(activator,res_z)))
res_a

array([1, 0, 0, 0])